package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * BusinessCategoryDo generated by Vivek
 */

@Entity
@Table(name = "business_category")
public class BusinessCategoryDo implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "business_category_pkey")
    private long businessCategoryPkey;

    @Column(name = "category_name")
    private String categoryName;

    @Column(name = "category_description")
    private String categoryDescription;

    @Column(name = "category_type")
    private String categoryType;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

//    @OneToMany(mappedBy = "")
//  private Set<MerchantBusinessCategoryMapDo> merchantBusinessCategoryMaps = new HashSet<MerchantBusinessCategoryMapDo>(0);

    public BusinessCategoryDo() {
    }

    public long getBusinessCategoryPkey() {
        return this.businessCategoryPkey;
    }

    public void setBusinessCategoryPkey(long businessCategoryPkey) {
        this.businessCategoryPkey = businessCategoryPkey;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryDescription() {
        return this.categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public String getCategoryType() {
        return categoryType;
    }

    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

}


