package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * CampaignPlansDo generated by Vivek
 */

@Entity
@Table(name = "campaign_plans")
public class CampaignPlansDo implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "campaign_plans_pkey")
    private long campaignPlansPkey;

    @Column(name = "plan_name")
    private String planName;

    @Column(name = "plan_description")
    private String planDescription;

    @Column(name = "cost")
    private double cost;

    @Column(name = "cost_per_impression")
    private Double costPerImpression;

    @Column(name = "cost_per_click")
    private Double costPerClick;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

//  private Set<MerchantCampaignPlansMapDo> merchantCampaignPlansMaps = new HashSet<MerchantCampaignPlansMapDo>(0);


    public long getCampaignPlansPkey() {
        return campaignPlansPkey;
    }

    public void setCampaignPlansPkey(long campaignPlansPkey) {
        this.campaignPlansPkey = campaignPlansPkey;
    }

    public String getPlanName() {
        return planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public String getPlanDescription() {
        return planDescription;
    }

    public void setPlanDescription(String planDescription) {
        this.planDescription = planDescription;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public Double getCostPerImpression() {
        return costPerImpression;
    }

    public void setCostPerImpression(Double costPerImpression) {
        this.costPerImpression = costPerImpression;
    }

    public Double getCostPerClick() {
        return costPerClick;
    }

    public void setCostPerClick(Double costPerClick) {
        this.costPerClick = costPerClick;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
}


