package com.marketeer.redemption.mvc.entity;

import javax.persistence.*;
import java.util.Date;


/**
 * CityDo generated by Vivek
 */

@Entity
@Table(name = "city")
public class CityDo implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "city_pkey")
    private long cityPkey;

    @Column(name = "city")
    private String city;

    @Column(name = "state")
    private String state;

    @Column(name = "country")
    private String country;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "modified_by")
    private String modifiedBy;

    @Column(name = "modified_on")
    private Date modifiedOn;

//    private Set<MerchantBranchDetailDo> merchantBranchDetails = new HashSet<MerchantBranchDetailDo>(0);
//    private Set<MerchantDo> merchants = new HashSet<MerchantDo>(0);
//    private Set<LocationsDo> locationses = new HashSet<LocationsDo>(0);


    public long getCityPkey() {
        return cityPkey;
    }

    public void setCityPkey(long cityPkey) {
        this.cityPkey = cityPkey;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedOn() {
        return modifiedOn;
    }

    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
}
