package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;
import java.util.List;

/**
 * CouponDo generated by Vivek
 */

@Entity
@Table(name = "coupon")
public class CouponDo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "coupon_id_pkey")
    private long couponIdPkey;

    @Column(name = "coupon_code")
    private String couponCode;

    @Column(name = "coupon_prefix")
    private String couponPrefix;

    @Column(name = "coupon_start_value")
    private long couponStartValue;

    @Column(name = "coupon_end_value")
    private long couponEndValue;

    @Column(name = "coupon_current_value")
    private long couponCurrentValue;

    @Column(name = "is_coupon_fixed")
    private int isCouponFixed;

    @Column(name = "number_of_coupons")
    private long numberOfCoupons;

    @Column(name = "redemption_per_user")
    private int redemptionPerUser;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @Column(name = "number_of_redemption")
    private long numberOfRedemption;

    @Column(name = "coupon_rendered")
    private long couponRendered;

    @Column(name = "deal_status")
    private int dealStatus;

    @Column(name = "deal_description")
    private String dealDescription;

    @Column(name = "is_coupon_external")
    private int isCouponExternal;

    @Column(name = "coupon_url")
    private String couponUrl;

    @Column(name = "deal_code")
    private String dealCode;

    @Column(name = "campaign_type")
    private String campaignType;

    @OneToMany(mappedBy = "coupon")
    private List<MerchantBranchDealsDo> merchantBranchDealsDoList;

    public CouponDo() {
        this.createdOn = this.updatedOn = new Date();
    }

    public CouponDo(int isCouponFixed, String couponPrefix, int dealStatus, String dealDescription, String campaignType, String createdBy, String updatedBy) {
        this.isCouponFixed = isCouponFixed;
        this.couponPrefix = couponPrefix;
        this.dealStatus = dealStatus;
        this.dealDescription = dealDescription;
        this.campaignType = campaignType;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdOn = this.updatedOn = new Date();

        this.isCouponExternal = 0;
        this.numberOfCoupons = 0;
        this.numberOfRedemption = 0;
        this.couponRendered = 0;


    }

    public long getCouponIdPkey() {
        return couponIdPkey;
    }

    public void setCouponIdPkey(long couponIdPkey) {
        this.couponIdPkey = couponIdPkey;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public String getCouponPrefix() {
        return couponPrefix;
    }

    public void setCouponPrefix(String couponPrefix) {
        this.couponPrefix = couponPrefix;
    }

    public long getCouponStartValue() {
        return couponStartValue;
    }

    public void setCouponStartValue(long couponStartValue) {
        this.couponStartValue = couponStartValue;
    }

    public long getCouponEndValue() {
        return couponEndValue;
    }

    public void setCouponEndValue(long couponEndValue) {
        this.couponEndValue = couponEndValue;
    }

    public long getCouponCurrentValue() {
        return couponCurrentValue;
    }

    public void setCouponCurrentValue(long couponCurrentValue) {
        this.couponCurrentValue = couponCurrentValue;
    }

    public int getIsCouponFixed() {
        return isCouponFixed;
    }

    public void setIsCouponFixed(int isCouponFixed) {
        this.isCouponFixed = isCouponFixed;
    }

    public long getNumberOfCoupons() {
        return numberOfCoupons;
    }

    public void setNumberOfCoupons(long numberOfCoupons) {
        this.numberOfCoupons = numberOfCoupons;
    }

    public int getRedemptionPerUser() {
        return redemptionPerUser;
    }

    public void setRedemptionPerUser(int redemptionPerUser) {
        this.redemptionPerUser = redemptionPerUser;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public long getNumberOfRedemption() {
        return numberOfRedemption;
    }

    public void setNumberOfRedemption(long numberOfRedemption) {
        this.numberOfRedemption = numberOfRedemption;
    }

    public long getCouponRendered() {
        return couponRendered;
    }

    public void setCouponRendered(long couponRendered) {
        this.couponRendered = couponRendered;
    }

    public int getDealStatus() {
        return dealStatus;
    }

    public void setDealStatus(int dealStatus) {
        this.dealStatus = dealStatus;
    }

    public String getDealDescription() {
        return dealDescription;
    }

    public void setDealDescription(String dealDescription) {
        this.dealDescription = dealDescription;
    }

    public int getIsCouponExternal() {
        return isCouponExternal;
    }

    public void setIsCouponExternal(int isCouponExternal) {
        this.isCouponExternal = isCouponExternal;
    }

    public String getCouponUrl() {
        return couponUrl;
    }

    public void setCouponUrl(String couponUrl) {
        this.couponUrl = couponUrl;
    }

    public String getDealCode() {
        return dealCode;
    }

    public void setDealCode(String dealCode) {
        this.dealCode = dealCode;
    }

    public String getCampaignType() {
        return campaignType;
    }

    public void setCampaignType(String campaignType) {
        this.campaignType = campaignType;
    }


    public List<MerchantBranchDealsDo> getMerchantBranchDealsDoList() {
        return merchantBranchDealsDoList;
    }

    public void setMerchantBranchDealsDoList(List<MerchantBranchDealsDo> merchantBranchDealsDoList) {
        this.merchantBranchDealsDoList = merchantBranchDealsDoList;
    }
}