package com.marketeer.redemption.mvc.entity;
// Generated 13 Feb, 2011 8:45:13 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;
import java.util.Date;

/**
 * DealsCategoryDo generated by Vivek
 */

@Entity
@Table(name = "deals_category")
public class DealsCategoryDo implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "category_pkey")
    private long categoryPkey;

    @Column(name = "category_name")
    private String categoryName;

    @Column(name = "category_description")
    private String categoryDescription;

    @Column(name = "category_template")
    private String categoryTemplate;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;


//   private Set<MerchantBranchDealsDo> merchantBranchDealses = new HashSet<MerchantBranchDealsDo>(0);


    public long getCategoryPkey() {
        return categoryPkey;
    }

    public void setCategoryPkey(long categoryPkey) {
        this.categoryPkey = categoryPkey;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryDescription() {
        return categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public String getCategoryTemplate() {
        return categoryTemplate;
    }

    public void setCategoryTemplate(String categoryTemplate) {
        this.categoryTemplate = categoryTemplate;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
}


