package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * BranchOpenDaysDo generated by Vivek
 */

@Entity
@Table(name = "deals_valid_days")
public class DealsValidDaysDo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "dvd_pkey")
    private long dvdPkey;

    @Column(name = "day_id")
    private short dayId;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @ManyToOne
    @JoinColumn(name = "merchant_branch_deals_fkey")
    private MerchantBranchDealsDo merchantBranchDeals;


    public DealsValidDaysDo(short dayId, String createdBy, String updatedBy, MerchantBranchDealsDo merchantBranchDeals) {
        this.dayId = dayId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.merchantBranchDeals = merchantBranchDeals;
        this.createdOn = this.updatedOn = new Date();
    }

    public long getDvdPkey() {
        return dvdPkey;
    }

    public void setDvdPkey(long dvdPkey) {
        this.dvdPkey = dvdPkey;
    }

    public short getDayId() {
        return dayId;
    }

    public void setDayId(short dayId) {
        this.dayId = dayId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public MerchantBranchDealsDo getMerchantBranchDeals() {
        return merchantBranchDeals;
    }

    public void setMerchantBranchDeals(MerchantBranchDealsDo merchantBranchDeals) {
        this.merchantBranchDeals = merchantBranchDeals;
    }
}


