package com.marketeer.redemption.mvc.entity;
// Generated 13 Feb, 2011 8:45:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LocationsDo generated by hbm2java
 */


public class LocationsDo implements java.io.Serializable {


    private long locationPkey;
    private CityDo city;
    private String locationName;
    private Double latitude;
    private Double longitude;
    private Integer pinCode;
    private Boolean isMajorLocation;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;


//     private Set<AdvertUserDo> advertUsers = new HashSet<AdvertUserDo>(0);


}


