package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * MerchantBranchDetailDo generated by Vivek
 */

@Entity
@Table(name = "merchant_selection")
public class MerchantSelectionDo implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "merchant_selection_pkey")
    private long merchantSelectionPkey;

    @Column(name = "start_subscription_date")
    private Date startSubscriptionDate;

    @Column(name = "merchant_validity")
    private Date merchantValidity;

    @Column(name = "is_subscription_fee_deposit")
    private short isSubscriptionFeeDeposit;

    @Column(name = "has_money_saver_pack")
    private short hasMoneySaverPack;

    @Column(name = "merchant_total_branches")
    private long merchantTotalBranches;

    @Column(name = "merchant_total_deals")
    private long merchantTotalDeals;

    @Column(name = "money_saver_pack_category")
    private String moneySaverPackCategory;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @ManyToOne
    @JoinColumn(name = "merchant_fkey")
    private MerchantDo merchant;

    public long getMerchantSelectionPkey() {
        return merchantSelectionPkey;
    }

    public void setMerchantSelectionPkey(long merchantSelectionPkey) {
        this.merchantSelectionPkey = merchantSelectionPkey;
    }

    public Date getStartSubscriptionDate() {
        return startSubscriptionDate;
    }

    public void setStartSubscriptionDate(Date startSubscriptionDate) {
        this.startSubscriptionDate = startSubscriptionDate;
    }

    public Date getMerchantValidity() {
        return merchantValidity;
    }

    public void setMerchantValidity(Date merchantValidity) {
        this.merchantValidity = merchantValidity;
    }

    public short getIsSubscriptionFeeDeposit() {
        return isSubscriptionFeeDeposit;
    }

    public void setIsSubscriptionFeeDeposit(short isSubscriptionFeeDeposit) {
        this.isSubscriptionFeeDeposit = isSubscriptionFeeDeposit;
    }

    public short getHasMoneySaverPack() {
        return hasMoneySaverPack;
    }

    public void setHasMoneySaverPack(short hasMoneySaverPack) {
        this.hasMoneySaverPack = hasMoneySaverPack;
    }

    public long getMerchantTotalBranches() {
        return merchantTotalBranches;
    }

    public void setMerchantTotalBranches(long merchantTotalBranches) {
        this.merchantTotalBranches = merchantTotalBranches;
    }

    public long getMerchantTotalDeals() {
        return merchantTotalDeals;
    }

    public void setMerchantTotalDeals(long merchantTotalDeals) {
        this.merchantTotalDeals = merchantTotalDeals;
    }

    public String getMoneySaverPackCategory() {
        return moneySaverPackCategory;
    }

    public void setMoneySaverPackCategory(String moneySaverPackCategory) {
        this.moneySaverPackCategory = moneySaverPackCategory;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public MerchantDo getMerchant() {
        return merchant;
    }

    public void setMerchant(MerchantDo merchant) {
        this.merchant = merchant;
    }
}


