package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * MerchantBusinessCategoryMapDo generated by Vivek
 */

@Entity
@Table(name = "merchant_business_category_map")
public class MerchantBusinessCategoryMapDo implements java.io.Serializable {


    @Id
    @GeneratedValue
    @Column(name = "merchant_business_category_map_pkey")
    private long merchantBusinessCategoryMapPkey;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @ManyToOne
    @JoinColumn(name = "merchant_fkey")
    private MerchantDo merchant;

    @ManyToOne
    @JoinColumn(name = "business_category_fkey")
    private BusinessCategoryDo businessCategory;

    public long getMerchantBusinessCategoryMapPkey() {
        return merchantBusinessCategoryMapPkey;
    }

    public void setMerchantBusinessCategoryMapPkey(long merchantBusinessCategoryMapPkey) {
        this.merchantBusinessCategoryMapPkey = merchantBusinessCategoryMapPkey;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public MerchantDo getMerchant() {
        return merchant;
    }

    public void setMerchant(MerchantDo merchant) {
        this.merchant = merchant;
    }

    public BusinessCategoryDo getBusinessCategory() {
        return businessCategory;
    }

    public void setBusinessCategory(BusinessCategoryDo businessCategory) {
        this.businessCategory = businessCategory;
    }
}


