package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * MerchantBranchDealsBusinessCategoryMapDo generated by Vivek
 */

@Entity
@Table(name = "merchant_branch_deals_business_category_map")
public class MerchantBranchDealsBusinessCategoryMapDo implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "merchant_branch_deals_business_category_pkey")
    private long merchantBranchDealsBusinessCategoryPkey;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;


    @ManyToOne
    @JoinColumn(name = "merchant_branch_deals_fkey")
    private MerchantBranchDealsDo merchantBranchDeals;

    @ManyToOne
    @JoinColumn(name = "business_category_fkey")
    private BusinessCategoryDo businessCategory;


    public long getMerchantBranchDealsBusinessCategoryPkey() {
        return merchantBranchDealsBusinessCategoryPkey;
    }

    public void setMerchantBranchDealsBusinessCategoryPkey(long merchantBranchDealsBusinessCategoryPkey) {
        this.merchantBranchDealsBusinessCategoryPkey = merchantBranchDealsBusinessCategoryPkey;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public MerchantBranchDealsDo getMerchantBranchDeals() {
        return merchantBranchDeals;
    }

    public void setMerchantBranchDeals(MerchantBranchDealsDo merchantBranchDeals) {
        this.merchantBranchDeals = merchantBranchDeals;
    }

    public BusinessCategoryDo getBusinessCategory() {
        return businessCategory;
    }

    public void setBusinessCategory(BusinessCategoryDo businessCategory) {
        this.businessCategory = businessCategory;
    }
}


