package com.marketeer.redemption.mvc.entity;


import javax.persistence.*;
import java.util.Date;

/**
 * MerchantBranchDetailsBranchDealsMapDo generated by Vivek
 */

@Entity
@Table(name = "merchant_branch_details_branch_deals_map")
public class MerchantBranchDetailsBranchDealsMapDo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "m_bdetails_bdeals_pkey")
    private long MBdetailsBdealsPkey;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @ManyToOne
    @JoinColumn(name = "merchant_branch_details_fkey")
    private MerchantBranchDetailDo merchantBranchDetail;

    @ManyToOne
    @JoinColumn(name = "merchant_branch_deals_fkey")
    private MerchantBranchDealsDo merchantBranchDeals;

    public long getMBdetailsBdealsPkey() {
        return MBdetailsBdealsPkey;
    }

    public void setMBdetailsBdealsPkey(long MBdetailsBdealsPkey) {
        this.MBdetailsBdealsPkey = MBdetailsBdealsPkey;
    }

    public MerchantBranchDetailDo getMerchantBranchDetail() {
        return merchantBranchDetail;
    }

    public void setMerchantBranchDetail(MerchantBranchDetailDo merchantBranchDetail) {
        this.merchantBranchDetail = merchantBranchDetail;
    }

    public MerchantBranchDealsDo getMerchantBranchDeals() {
        return merchantBranchDeals;
    }

    public void setMerchantBranchDeals(MerchantBranchDealsDo merchantBranchDeals) {
        this.merchantBranchDeals = merchantBranchDeals;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
}


